# Generated by Django 5.2.9 on 2026-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_card_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.TextField(default='black', max_length=20),
        ),
    ]
