# Generated by Django 5.2.9 on 2026-01-05 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_authors_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('bio', models.TextField(max_length=500)),
                ('author_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_1.authors')),
            ],
        ),
    ]
